@ECHO OFF

ECHO "Cleaning Build"

CALL gradlew clean

ECHO "Deploying Nodes....."

CALL gradlew.bat deployNodes

ECHO "Nodes Deployed, Running the Ndoes .."

CALL build/nodes/runnodes.bat >NUL

set /A COUNTER=0
set /A MAX_COUNTER=300

:NOTARY_START_CHECK
CALL netstat -ano | findStr "10053" | findStr "LISTENING" >NUL
if %ERRORLEVEL% equ 0 goto STARTED

set /A COUNTER=%COUNTER%+10
ping -n 10 127.0.0.1>nul
if %COUNTER%  gtr %MAX_COUNTER% goto ERROR_AND_EXIT
goto NOTARY_START_CHECK

:STARTED
echo NOTARY STARTED



:FA_NODE_START_CHECK
CALL netstat -ano | findStr "10046" | findStr "LISTENING" >NUL
if %ERRORLEVEL% equ 0 goto FA_STARTED

set /A COUNTER=%COUNTER%+10
ping -n 10 127.0.0.1>nul
if %COUNTER%  gtr %MAX_COUNTER% goto ERROR_AND_EXIT
goto FA_NODE_START_CHECK

:FA_STARTED
echo FA STARTED



:BANK_NODE_START_CHECK
CALL netstat -ano | findStr "10049" | findStr "LISTENING" >NUL
if %ERRORLEVEL% equ 0 goto BANK_NODE_STARTED

set /A COUNTER=%COUNTER%+10
ping -n 10 127.0.0.1>nul
if %COUNTER%  gtr %MAX_COUNTER% goto ERROR_AND_EXIT
goto BANK_NODE_START_CHECK

:BANK_NODE_STARTED
echo NOTARY STARTED



:CA_NODE_START_CHECK
CALL netstat -ano | findStr "10053" | findStr "LISTENING" >NUL
if %ERRORLEVEL% equ 0 goto CA_NODE_STARTED

set /A COUNTER=%COUNTER%+10
ping -n 10 127.0.0.1>nul
if %COUNTER%  gtr %MAX_COUNTER% goto ERROR_AND_EXIT
goto CA_NODE_START_CHECK

:CA_NODE_STARTED
echo CA NODE STARTED


START /B gradlew bootRunFA >NUL
START /B gradlew bootRunBank >NUL
START /B gradlew bootRunCA >NUL


set /A BOOT_COUNTER=0
set /A MAX_BOOT_COUNTER=300



:FA_BOOT_APP_START_CHECK
CALL netstat -ano | findStr "8080" | findStr "LISTENING" >NUL
if %ERRORLEVEL% equ 0 goto FA_BOOT_STARTED

set /A BOOT_COUNTER=%BOOT_COUNTER%+10
ping -n 10 127.0.0.1>nul
if %BOOT_COUNTER%  gtr %MAX_BOOT_COUNTER% goto ERROR_AND_EXIT
goto FA_BOOT_APP_START_CHECK

:FA_BOOT_STARTED
echo FA BOOT APP STARTED


:BANK_BOOT_APP_START_CHECK
CALL netstat -ano | findStr "8090" | findStr "LISTENING" >NUL
if %ERRORLEVEL% equ 0 goto BANK_BOOT_STARTED

set /A BOOT_COUNTER=%BOOT_COUNTER%+10
ping -n 10 127.0.0.1>nul
if %BOOT_COUNTER%  gtr %MAX_BOOT_COUNTER% goto ERROR_AND_EXIT
goto BANK_BOOT_APP_START_CHECK

:BANK_BOOT_STARTED
echo BANK BOOT APP STARTED


:CA_BOOT_APP_START_CHECK
CALL netstat -ano | findStr "8093" | findStr "LISTENING" >NUL
if %ERRORLEVEL% equ 0 goto CA_BOOT_APP_STARTED

set /A BOOT_COUNTER=%BOOT_COUNTER%+10
ping -n 10 127.0.0.1>nul
if %BOOT_COUNTER%  gtr %MAX_BOOT_COUNTER% goto ERROR_AND_EXIT
goto CA_BOOT_APP_START_CHECK

:CA_BOOT_APP_STARTED
echo CA BOOT APP STARTED

echo "::::::::::::::::ALL APPS AND SERVER STARTED::::::::::::::"
exit /B 0

:ERROR_AND_EXIT
echo "StartUp taking too much time"
exit /B -1

